- hosts: all
  become: true
  tasks:
    - name: Setting up yum for Docker
      yum_repository:
        name: docker
        description: DOCKER YUM repo
        file: docker_repo
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        enabled: 1
        gpgcheck: 1
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Installing Docker
      yum: 
        name: docker-ce
        update_cache: yes

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Install pip
      package:
        name: python2-pip
        state: present 

    - name: Install docker-py
      pip:
        name: docker-py    

    - name: Pull raktim00/httpd-server image
      community.general.docker_image:
        name: raktim00/httpd-server
        source: pull

    - name: Create a directory if it does not exist
      file:
        path: /etc/http_files
        state: directory

    - name: Create a httpd server container
      community.general.docker_container:
        name: webserver
        image: raktim00/httpd-server
        container_default_behavior: compatibility
        ports:
          - "8085:80"
        volumes:
          - /etc/http_files/:/var/www/html    

    - name: Deploying own html file
      copy:
        content: "Hello World, Welcome to my website, running inside docker container created by my own custom docker image"
        dest: /etc/http_files/hello.html

    - name: Stop firewalld.
      service:
        name: firewalld
        state: stopped        